spring:
  profiles:
    include: feign,task,actuator,common
  config:
    import: classpath:system-config.properties
  application:
    name: demo-01-service

server:
  shutdown: graceful
  port: 8081
  servlet:
    context-path: "/"