spring:
  profiles:
    include: feign,task,actuator,common,message
  config:
    import: classpath:system-config.properties, classpath:application-message.yaml
  application:
    name: demo-01-service

server:
  shutdown: graceful
  port: 8081
  servlet:
    context-path: "/"