########################### feign
feign:
  client:
    config:
      jax-rs:
#        Millis
        connectTimeout: 3600
        readTimeout: 3600
        errorDecoder:
        metrics:
          enabled: true
        followRedirects: true
        contract: feign.jaxrs2.JAXRS2Contract
#
#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
########################### loadbalancer
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
      health-check:
        initial-delay: 1m
        refetch-instances: true
        refetch-instances-interval: 25s




########################### jackson
#  jackson:
#    #日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      #格式化输出
#      indent_output: true
#      #忽略无法转换的对象
#      fail_on_empty_beans: true
#    #设置空如何序列化
#    defaultPropertyInclusion: NON_EMPTY
#    deserialization:
#      #允许对象忽略json中不存在的属性
#      fail_on_unknown_properties: true
#    parser:
#      #允许出现特殊字符和转义符
#      allow_unquoted_control_chars: true
#      #允许出现单引号
#      allow_single_quotes: true